Use dynamic namespace and the right roles perms in the Helm chart
sighupio/permission-manager pull request #139
Opened 2023-01-26 16:31 UTC by luigibarbato

Thanks to @ralgozino we have identified a number of issues within permission manager behavior regarding role creation in that the service account namespace is hardcoded on the backend side. In contrast, the role subjects namespace is hardcoded on the frontend side. Since this issue needs to be well analyzed and discussed, this PR implements a workaround to curb the problem in the short term.

In addition, we have identified that the default values of permissions assigned to different roles in the helm chart are not the correct ones.

2023-01-27 10:16 UTC, ralgozino requested changes
Please double-check the dynamic seeds, There are some permissions missing compared to the `deployments/kubernets/seeds/seed.yml` file.

2023-01-27 13:23 UTC, luigibarbato commented on web-client/src/components/Header.tsx
> +          Permission Manager
🤣

2023-01-31 14:19 UTC, ralgozino approved these changes
LGTM 🎸

2023-01-31 14:22 UTC, luigibarbato commented
> LGTM 🎸

💣

2023-01-31 14:23 UTC, merged